### ISSUE TITLE
Error parsing on internal server error

### ISSUE THREAD

**Issue by vladzloteanu** [Goracash/goracash-api-php-client#4]
When the server responds with:
```
[
     "status" => "error",
     "errors" => [
       "Erreur interne du serveur",
     ],
     "warnings" => [],
     "success" => [],
     "info" => [],
   ]
```

the error parsing code does not handle it gracefully:
https://github.com/Goracash/goracash-api-php-client/blob/483e865fdba35978ec82dbc432a9225aee1042c3/src/Service.php#L106

`Notice: Undefined index: message in /Users/vlad/wrk/dolead/plugman/src/vendor/goracash/apiclient/src/Service.php on line 106`

**Comment by davaxi** [comment]
Fix in release 1.0.11-beta
Thanks
