### ISSUE TITLE
PHP7 : Compile Error: Cannot use 'Void' as class name as it is reserved

### ISSUE THREAD

**Issue by l3ackslash0** [Goracash/goracash-api-php-client#6]
It seems that one class has the same name as the keyword "void" which is reserved in PHP 7.
Could it be possible to rename this class in order to avoid this kind of fatal error ?

The complete error id here :

**Compile Error: Cannot use 'Void' as class name as it is reserved
500 Internal Server Error - FatalErrorException**

Stack Trace
in vendor/goracash/apiclient/src/Logger/Void.php at line 26   -

`
class Void extends Primary 
{ 
    /** 
     * {@inheritdoc} 
`

**Comment by l3ackslash0** [comment]
Hello!

I added a pull request to fix this problem, could you check if it's ok for you?

Thax ! :)

**Comment by davaxi** [comment]
Your pull request has bean merged. Thanks 👍
